### ISSUE TITLE
Optional properties cannot be added with partial param unless defined in the factory

### ISSUE THREAD

**Issue by JoseLion** [rodmax/factory-t#110]
Hi @rodmax,

First, I wanted to thank you for this great library. Lightweight, with strong typings, and it has covered all my use cases so far. Awesome job!

I found an issue when working with optional properties, though. Usually, optional properties are not included in the factory definition (that's why they are optional, right?). However, at this point, it's not possible to add a value for an optional property using the `partial` param of `.item(..)` for example.

The only workaround I found is to set the property in the factory definition as `undefined`. But IMHO, I think that defies the purpose of an optional property, and it's also a little cumbersome to add `undefined` for all optional properties to avoid this issue.

Here's an example in a small playground I created: https://codesandbox.io/s/factory-t-playground-r9ueq?file=/src/index.ts

Let me know if this makes sense to you. Also, I'll be happy to help out with a PR if you point me in the right direction.

Cheers!

**Comment by rodmax** [comment]
Hi @JoseLion. Thank You for feedback.
First. Yes. It makes sense for this library because of one of the base requirement: *strongly follow to target type*

I quickly look into implementation and see that approach for optional already exists:

```ts
import { factoryT, FactoryT, fields } from 'factory-t';

interface WithOptional {
  password?: string;
}
const factory = factoryT<WithOptional>({
  password: fields.optional('default'),
});
```

**BUT** it is not working properly and just makes typing trick, not really makes field optional 😞 

I believe it's needed to enhance `fields.optional()` approach something like so:

```ts
const factory = factoryT<{key?: string}>({
  key: fields.optional(fields.NOT_SET_VALUE)
  // or
  key: fields.optional(), // empty argument means that by default key is missing in generated item
  key: undefined, // this last not appreciable due to not recognizes {key: string | undefined} with {key?: string}
})

console.log(factory.item())
// {} instead of {key: undefined}
console.log(factory.item({key: 'hello'}))
// {key: 'hello'}
```
I see some difficulties with typing of such an approach <br>
I play with it evening and reply

**Comment by rodmax** [comment]
>  Usually, optional properties are not included in the factory definition

Oh, I missed one point provided by you 🤔. Right now I am not sure it may be implementable but I promise think about it too

**Comment by rodmax** [comment]
@JoseLion  look at this solution: https://github.com/rodmax/factory-t/pull/111
Will it solve the problem?

if something confuses you or you have ideas for improvement(semantic/API), then do not hesitate, and let me now
